version: '3'

services:
  frontend:
    build: ./admin-frontend
    container_name: market-admin
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./admin-frontend/src:/usr/src/app/src
    networks:
      - market-network

  api:
    build: ./api
    container_name: market-api
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
    restart: unless-stopped
    environment:
      - PORT=3001
      - HOST=http://front-market.ru
      - MONGO_URL=mongodb://api_db:27017/marketDB
    depends_on:
      - api_db
    networks:
      - market-network
  
  api_db:
    image: mongo
    container_name: market-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ps123
      MONGO_INITDB_DATABASE: marketDB
    volumes:
      - mongodb_api:/data/db
    networks:
      - market-network

  nginx:
    image: nginx:stable-alpine
    container_name: market-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - market-network

volumes:
  mongodb_api:

networks:
  market-network:
    driver: bridge